-- CreateEnum
CREATE TYPE "MealType" AS ENUM ('FASTING', 'AFTER_BREAKFAST', 'AFTER_AM_SNACK', 'AFTER_LUNCH', 'AFTER_PM_SNACK', 'AFTER_DINNER', 'AFTER_NIGHT_SNACK', 'BEDTIME', 'POST_EXERCISE', 'OTHER');

-- CreateTable
CREATE TABLE "GlucoseLog" (
    "id" TEXT NOT NULL,
    "time" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "value" INTEGER NOT NULL,
    "mealType" "MealType" NOT NULL,
    "notes" TEXT,
    "userId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "GlucoseLog_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "GlucoseLog" ADD CONSTRAINT "GlucoseLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
